language: java
script:
  - jdk_switcher use oraclejdk8
  - # do stuff with Java 8
  - jdk_switcher use openjdk8
  - # do stuff with open Java 8
after_success:
- mvn cobertura:cobertura coveralls:report
